### ISSUE TITLE
[Feature] Allow to manage vpc.extraCIDRs on existing clusters

### ISSUE THREAD

**Issue by steffakasid** [eksctl-io/eksctl#5573]
### What feature/behavior/change do you want?

Provide the possibility to change `vpc.extraCIDRs` on existing clusters.

### Why do you want this feature?

We have a cluster with:
```
vpc:
  clusterEndpoints:
    publicAccess: false
    privateAccess: true
  extraCIDRs:
     - 1.2.3.4/32
     - 5.6.7.8/32
```

All team-members which are allowed to connect to that cluster are added within `vpc.extraCIDRs`. From time to time someone leaves or joins the team and therefore we need the ability to manage  the `vpc.extraCIDRs` to add additional CIDRs or remove some of them.

Regards
Steffen
