### ISSUE TITLE
[Feature] Install cert-manager when installing ADOT addon

### ISSUE THREAD

**Issue by emboss64** [eksctl-io/eksctl#6171]
### What feature/behavior/change do you want?
cert-manager is a prerequisite for the adot addon. If you try to include adot in an initial cluster config you receive the following error: `cert-manager is not installed on this cluster. During preview, you are required to have previously installed cert-manager.`

Just installing the base cert-manager chart is enough to make it work: `kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.yaml`

### Why do you want this feature?
Simplify the provisioning process

**Comment by Himangini** [comment]
@emboss64 Can you provide steps for how you are installing ADOT with eksctl? Are you following these instructions https://docs.aws.amazon.com/eks/latest/userguide/adot-manage.html#adot-install ?

**Comment by emboss64** [comment]
Yes. However what's missing to get the addon working with a fresh cluster would be the prereqs/cert-manager part (https://docs.aws.amazon.com/eks/latest/userguide/adot-reqts.html)

**Comment by dnutels** [comment]
Allow me to interject.... @Himangini I am not sure I understand your "Yes". 

Based on your initial response you used `eksctl` to install the cluster and the add-ons. So the answer to the above question should be "No" as it requires you to use either AWS Console or AWS CLI to install add-ons separately from the cluster.

The following, today, doesn't work -- the cluster provision fails with a cryptic message:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: some-cluster
  region: eu-west-1
  version: '1.24'

... # skipping network setup

iam:
  withOIDC: true

... # skipping some irrelvant configuration, like node groups or fargate profiles

addons:
  - name: vpc-cni
  - name: kube-proxy
  - name: coredns
  - name: adot
```

If I remove `name: adot` it works, so the culprit is clear.
