### ISSUE TITLE
[Bug] eksctl doesn't use the port specified in the server: field in $KUBECONFIG

### ISSUE THREAD

**Issue by bitva77** [eksctl-io/eksctl#6405]
In my KUBECONFIG I have like:  `server: https://45ABCE83A23FBBC3BE1D9FC4DA203994.gr7.us-west-2.eks.amazonaws.com:5560`

We hit `45ABCE83A23FBBC3BE1D9FC4DA203994.gr7.us-west-2.eks.amazonaws.com` via SSM port forwarding through localhost.  So in my `/etc/hosts` I have:  `127.0.0.1 45ABCE83A23FBBC3BE1D9FC4DA203994.gr7.us-west-2.eks.amazonaws.com`

However, when `eksctl create iamserviceaccount` is run we get this error:

```
Error: checking whether serviceaccount "external-secrets/external-secrets-operator" exists: Get "https://45ABCE83A23FBBC3BE1D9FC4DA203994.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/external-secrets/serviceaccounts/external-secrets-operator": dial tcp 127.0.0.1:443: connect: connection refused
```

While the error message is technically correct because you can't hit the API via port 443, it should really be using the port that's defined in the KUBECONFIG file

**Comment by yuxiang-zhang** [comment]
Hello @bitva77 do you mind sharing how to reproduce this issue?

**Comment by bitva77** [comment]
Not sure you want to get into the whole SSM port forwarding thing but basically we put our EKS cluster in a private - non-routable VPC.  We connect to a bastion  host via SSM and do port forwarding to access the K8s API (since it's private).

`kubeconfig`:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: long-ass-string
    server: https://46ABCE83A23FBBC3BE1D9FC4DA203988.gr7.us-west-2.eks.amazonaws.com:5560
  name: arn:aws:eks:us-west-2:123456789:cluster/general
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:123456789:cluster/general
    user: arn:aws:eks:us-west-2:123456789:cluster/general
  name: arn:aws:eks:us-west-2:123456789:cluster/general
current-context: arn:aws:eks:us-west-2:123456789:cluster/general
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:123456789:cluster/general
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - general
      command: aws
```

note the port `5560` in the `.clusters.cluster.server` section.

put this in `/etc/hosts`:

`127.0.0.1 46ABCE83A23FBBC3BE1D9FC4DA203988.gr7.us-west-2.eks.amazonaws.com`

Run the SSM port forward:

`sudo -E -b aws ssm start-session --target i-04c1551d8c2e7291c --document-name AWS-StartPortForwardingSessionToRemoteHost --parameters '{"host":["46ABCE83A23FBBC3BE1D9FC4DA203988.gr7.us-west-2.eks.amazonaws.com"],"portNumber":["443"], "localPortNumber":["5560"]}'`

Now run `kubectl get nodes` and it works fine.

Now create a service account with `eksctl` and it fails with the error above.

It looks like `eksctl` is getting the correct server and is using the correct IP via `/etc/hosts` however it's omitting the port.  It's assuming port 443 no matter what.

Happy to provide more info if needed...
