### ISSUE TITLE
[Feature] Support OverrideBootstrapcommand for Windows Custom AMI

### ISSUE THREAD

**Issue by itshili** [eksctl-io/eksctl#6463]
### What feature/behavior/change do you want?

Could you please provide add support for using the OverrideBootstrapcommand to create self-managed nodegroups using  `Windows Custom AMI` 
### Why do you want this feature?

Looking at the documentation for eksctl: Custom AMI support, I see that following

1. The overrideBootstrapCommand is acknowledged for AmazonLinux2 and Ubuntu nodes.
2. Only the `Bottlerocket custom AMI support¶`, is explicitly documented as not supported.
3. eksctl requires AMI Family to be explicitly set via config file or via --node-ami-family CLI flag, whenever working with a custom AMI.

There is no clarification to explain that Windows AMI as not supported. 

While using `eksctl version 0.128.0`, I am able to create a nodegroup using the following configuration file: 
````
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: <clustername>
  region: ap-south-1

nodeGroups:
  - name: windows-mng-custom-eksctl-0-128-0-simple
    instanceType: c5.xlarge
    minSize: 1
    volumeSize: 50
    amiFamily: WindowsServer2019FullContainer
    ami: ami-09915a026cc8732d2
````
Then I observed the following results: 
 -  Nodegroup CFN stack generated with auto generated userdata encrypted
 -  Generated NodeGroupLaunchTemplate has the Base64-encoded user data decoded for readability when observed on the EC2 console
 -  NodeGroupLaunchTemplate used to launch the EC2 instance and instance join the cluster successfully 

However, if were to use copy the same `userdata` from the `NodeGroupLaunchTemplate` gerarated from the CFN stack above and comment out the `amiFamily` parameter (see sample below)
````
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: <clustername>
  region: ap-south-1

nodeGroups:
  - name: windows-mng-custom-eksctl-0-128-0-simple
    instanceType: c5.xlarge
    minSize: 1
    volumeSize: 50  
    ami: ami-09915a026cc8732d2
    overrideBootstrapCommand: |
        <powershell>
        [string]$EKSBootstrapScriptFile = "$env:ProgramFiles\Amazon\EKS\Start-EKSBootstrap.ps1"
        & $EKSBootstrapScriptFile -EKSClusterName "<clustername>"
        </powershell>
````

Then I observed the following results: 
 -  Nodegroup CFN stack generated with auto generated userdata encrypted
 -  Generated NodeGroupLaunchTemplate user data remains encoded with same value shown on the CFN stack
 -  NodeGroupLaunchTemplate used to launch the EC2 instance and instance are not able to join the cluster successfully. 

I understand in this second scenrio, the CFN stack was launch with the assumption the default `--node-ami-family=AmazonLinux2`. However, when reviewing the stack differences, the main key is on the base64 Decoding process of which the First stack show that it is possible to decode the `userdata` for `amiFamily: WindowsServer2019FullContainer`. 

While using the lastest `ekctl versions`, I see the code returnns the following error
````
Error: could not create cluster provider from options: overrideBootstrapCommand is not supported for WindowsServer2019FullContainer nodegroups (path=nodeGroups[0].overrideBootstrapCommand)
````

However, the offocial docs on [Custom AMI support¶](https://eksctl.io/usage/custom-ami-support/) only states that `For Bottlerocket nodes, the overrideBootstrapCommand is not supported`

Based on the workflow of `eksctl version 0.128.0`, I believe it's possible to add support for the `overrideBootstrapCommand` if we fix the `userdata` decoding whe creating the `NodeGroupLaunchTemplate`. 

Noted related issues [#5248 ](https://github.com/weaveworks/eksctl/issues/5809), [#5809](https://github.com/weaveworks/eksctl/issues/5809) are marked as closed closed without any resolution,
