### ISSUE TITLE
[Help] Unable to create EKS managed nodegroups with custom Ubuntu AMI 

### ISSUE THREAD

**Issue by shivkumr** [eksctl-io/eksctl#6491]
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-eks-cluster
  region: us-east-1
  version: "1.24"

vpc:
  subnets:
    private:
      us-east-1a: 
        id: subnet-xxxxxx
      us-east-1b: 
        id: subnet-xxxxxxx
        
managedNodeGroups:
  - name:  worker
    labels: { nodeType: worker }
    instanceType: t2.xlarge
    desiredCapacity: 2
    ami: "ami-003237eb446483b5"
    privateNetworking: true
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh private-eks-cluster
```

$  eksctl create cluster -f ./cluster.yaml
Error: when using a custom AMI, amiFamily needs to be explicitly set via config file or via --node-ami-family flag

Trying to create a eks cluster using the ubuntu custom AMI from canonical, eksctl is complaining to set amiFamily, but when I add amiFamily then the request fails with the below error. 

```
$ eksctl create cluster -f ./cie-cluster-custom-ubuntu.yaml 
Error: cannot set amiFamily to Ubuntu2004 when using a custom AMI for managed nodes, only AmazonLinux2 is supported
```

**Comment by Sathyam-Unicommerce** [comment]
HI All, we are facing the same issue as well. I created a custom ubuntu 20.04 ami. Like @shivkumr mentioned, it expects an amiFamily field in the config file but denies any value except AmazonLinux2.

I have referred to the documentation available at [https://eksctl.io/usage/custom-ami-support/ ](https://eksctl.io/usage/custom-ami-support/) and have noticed that it does not mention any restrictions on using a custom Ubuntu AMI for creating a managed nodegroup. Furthermore, there are examples available on this page that demonstrate the creation of managed nodegroups using custom AMIs, which gives me the impression that using a custom Ubuntu AMI to create managed nodegroups should be possible.

I then tried creating an unmanaged nodegroup and although it was successfully created via eksctl, it did not get listed on the EKS console. However, I was able to run some pods on the unmanaged nodegroup, which worked as expected. I can see the nodes and pods in the workload section on eks console.

**Comment by Himangini** [comment]
@Sathyam-Unicommerce you're right, the docs example mentioned at https://eksctl.io/usage/custom-ami-support/  was added 2 years ago and I suspect this page info is outdated and needs work. We'll investigate this issue further 

```
nodeGroups:
  - name: ng1
    instanceType: m5.large
    amiFamily: AmazonLinux2
managedNodeGroups:
  - name: m-ng-2
    instanceType: m5.large
    amiFamily: Ubuntu2004
```

**Comment by jicowan** [comment]
I am having a similar issue. When I specify an AMI in my configuration file, it complains that I need to explicitly set the amiFamily. When I set the amiFamily, it says I need to add the overrideBootstrapCommand. 

cluster.yaml
```yaml
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: custom-vpc
  region: us-east-2
  version: "1.26"

vpc:
  id: "vpc-0540b5bb2f62f0b57"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    private:
      us-east-2a:
        id: "subnet-055f3a6c3ff813545"
        cidr: "10.0.128.0/20" # (optional, must match CIDR used by the given subnet)

      us-east-2b: 
        id: "subnet-01d641621d904f194"
        cidr: "10.0.144.0/20"

    public:
      us-east-2a: 
        id: "subnet-02c70740e6bcca41c"
        cidr: "10.0.0.0/20"

      us-east-2b: 
        id: "subnet-0f05d1763e92d0854"
        cidr: "10.0.16.0/20"

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    # amiFamily: AmazonLinux2
    # ami: ami-07a45fc1d4fd1092a
    #  overrideBootstrapCommand: 

managedNodeGroups:
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    privateNetworking: true
```

first error
```
Error: when using a custom AMI, amiFamily needs to be explicitly set via config file or via --node-ami-family flag
```

second error
```
Error: nodeGroups[0].overrideBootstrapCommand is required when using a custom AMI (nodeGroups[0].ami)
```
