### ISSUE TITLE
Error: no output "VPC" in stack "eksctl-prod-cluster"

### ISSUE THREAD

**Issue by Mohan18** [eksctl-io/eksctl#6501]
`cat on_demand_prod_nodegroup.yaml`

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-west-2


availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

nodeGroups:
 - name: prod-eks-test-cluster
   minSize: 1
   maxSize: 4
   volumeSize: 50
   volumeType: gp3
   desiredCapacity: 1
   instanceType: m5.xlarge
   privateNetworking: true
   labels:
     "dedicated": "test"
   taints:
     "dedicated": "test:NoSchedule"
   ssh:
     publicKeyPath: /kube/keys/aws_terraform.pub
   iam:
     attachPolicyARNs:
       - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
       - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
       - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
       - arn:aws:iam::aws:policy/AutoScalingFullAccess
       - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
       - arn:aws:iam::aws:policy/AmazonS3FullAccess

     withAddonPolicies:
       imageBuilder: true
       externalDNS: true
       certManager: true
       appMesh: true
       ebs: true
       fsx: true
       efs: true
       albIngress: true
       xRay: true
       cloudWatch: true
```

`Error: no output "VPC" in stack "eksctl-prod-cluster-nodegroup-prod-eks-test-cluster"`

```
➜  eksctl version 
0.136.0
```
