### ISSUE TITLE
UserData support for launch template 

### ISSUE THREAD

**Issue by ChaitDevOps** [eksctl-io/eksctl#6539]
### What feature/behavior/change do you want?

Would be nice to have a feature where we can pass "userdata" script to eksctl and have a way to pass the vars. Eksctl will create the launch template and assign it to the managed node group. 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-west-2

managedNodeGroups:
  - name: my-ng
    instanceType: t2.micro
    desiredCapacity: 2
    launchTemplate:
      name: my-launch-template
      version: "2"
      userData: |
        #!/bin/bash
        echo "My Var is ${FOO}"
    labels: { role: worker }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
```
`eksctl create nodegroup -f nodegroup.yaml --extra-vars FOO=BAR`

### Reason for feature?
I have to create eks cluster for 20+ AWS accounts. I'm planning to use a combination of eksctl and TF to achieve this. I have realized that eksctl is amazing at handling the entire networking and tagging the resources without much code. I'd like to use eksctl to create a launch template as well without having to create that piece separately. Let me know if i'm being too greedy or if the feature already exists.
