### ISSUE TITLE
[Feature] eksctl support to accommodate any new/full IAM policies for IAM Service accounts of CA and AWS Load balancer Controller

### ISSUE THREAD

**Issue by cooldudesam** [eksctl-io/eksctl#6616]
### What feature/behavior/change do you want?

Iam trying to update IAM service accounts for CA and AWS Load balancer controller via eksctl --config-file via below command. I dont see any changes in the corresponding IAM role and policies for CA and AWS Load balancer controller.  

```
$ eksctl update iamserviceaccount --config-file cluster_config.yaml --include kube-system/cluster-autoscaler --approve
2023-05-01 14:27:13 [ℹ]  combined include rules: kube-system/cluster-autoscaler
2023-05-01 14:27:13 [ℹ]  1 iamserviceaccount (kube-system/cluster-autoscaler) was included (based on the include/exclude rules)
2023-05-01 14:27:13 [ℹ]  3 iamserviceaccounts (kube-system/aws-load-balancer-controller, kube-system/ebs-csi-controller-sa, kube-system/efs-csi-controller-sa) were excluded (based on the include/exclude rules)
2023-05-01 14:27:26 [ℹ]  found set role name during creation eksctl-aws-clusterautoscaler-testclusterfor account cluster-autoscaler
2023-05-01 14:27:26 [ℹ]  1 task: { 1 task: { update IAMServiceAccount kube-system/cluster-autoscaler } }
2023-05-01 14:27:26 [ℹ]  updating policies for IAMServiceAccount kube-system/cluster-autoscaler
2023-05-01 14:27:27 [ℹ]  waiting for CloudFormation changeset "updating-policy-2cedd328-878a-436c-b852-e58a945bf5e0" for stack "eksctl-testcluster-addon-iamserviceaccount-kube-system-cluster-autoscaler"
2023-05-01 14:27:59 [ℹ]  waiting for CloudFormation changeset "updating-policy-2cedd328-878a-436c-b852-e58a945bf5e0" for stack "eksctl-testcluster-addon-iamserviceaccount-kube-system-cluster-autoscaler"
2023-05-01 14:28:01 [ℹ]  waiting for CloudFormation stack "eksctl-testcluster-addon-iamserviceaccount-kube-system-cluster-autoscaler"
2023-05-01 14:28:31 [ℹ]  waiting for CloudFormation stack "eksctl-testcluster-addon-iamserviceaccount-kube-system-cluster-autoscaler"
```

I even tried deleting and re-creating the IAMServiceAccount for CA via eksctl using below commands but still no changes in IAM policies.

`$eksctl delete iamserviceaccount --config-file cluster_config.yaml --include kube-system/cluster-autoscaler --approve`

`$ eksctl create iamserviceaccount --config-file cluster_config.yaml --include kube-system/cluster-autoscaler --approve`

Here is the snippet from my cluster_config_file

```
iam:
  serviceRoleARN: "arn:aws:iam::xxxxxxxxxxxxxx:role/eksClusterRole"
  fargatePodExecutionRolePermissionsBoundary: "arn:aws:iam::xxxxxxxxxxx:policy/RolesPermissionsBoundary"
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
    permissionsBoundary: "arn:aws:iam::xxxxxxxxxxxxx:policy/RolesPermissionsBoundary"
    roleName: eksctl-aws-lb-controller-testcluster
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    wellKnownPolicies:
      autoScaler: true
    permissionsBoundary: "arn:aws:iam::xxxxxxxxxxxx:policy/RolesPermissionsBoundary"
```

Here is how it should look like with new IAM perms:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:DescribeLaunchConfigurations",
        "autoscaling:DescribeScalingActivities",
        "autoscaling:DescribeTags",
        "ec2:DescribeInstanceTypes",
        "ec2:DescribeLaunchTemplateVersions"
      ],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": [
        "autoscaling:SetDesiredCapacity",
        "autoscaling:TerminateInstanceInAutoScalingGroup",
        "ec2:DescribeImages",
        "ec2:GetInstanceTypesFromInstanceRequirements",
        "eks:DescribeNodegroup"
      ],
      "Resource": ["*"]
    }
  ]
}
```

The github page for CA (1) says there are new IAM policies that I need to update in my cluster since Iam on EKS 1.24.

(1) https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md
```
$ eksctl version
0.139.0
```
As a workaround, I believe we should be able to create a separate custom policy and attach it to service account by using “attachPolicyARNs”, this will add separate policy apart from the default one which eksctl is attaching to the role.  

We have lot of clusters and dont want to manage additional IAM policy because we provision clusters via eksctl and the tool anyhow creates IAM serviceaccount and IAM role and adds necessary inline policies to the role.

### Why do you want this feature?

We would like to test below things and implement across approx 50 clusters and growing. Currently, these are a blocker for us.

1. Upgrade EKS from 1.24 to 1.25. (There are changes in IAM policies for CA and AWS Load Balancer Controller add-ons)
2. With EKS support for Kubernetes 1.24, the Cluster Autoscaler has been extended to support scale to zero for managed nodegroups and scales up automatically when we deploy a workload. 

Thanks,
Samba

**Comment by darkn3rd** [comment]
@cooldudesam Could you use triple backtiqs for expressing code or cli interactions, it is hard to read.

**Comment by joneidaws** [comment]
> As a workaround, I believe we should be able to create a separate custom policy and attach it to service account by using “attachPolicyARNs”, this will add separate policy apart from the default one which eksctl is attaching to the role.

@cooldudesam have you tried using the `attatchPolicy` directive as follows to attach your desired permissions to the role and bypass the default `wellKnownPolicies`. I agree the default policy can also be updated

```
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
      roleName: eksctl-aws-lb-controller-testcluster
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      attachPolicy: # optional
        Statement:
        - Effect: Allow
          Action:
          - autoscaling:DescribeAutoScalingGroups
          - autoscaling:DescribeAutoScalingInstances
          - autoscaling:DescribeLaunchConfigurations
          - autoscaling:DescribeScalingActivities
          - autoscaling:DescribeTags
          - ec2:DescribeInstanceTypes
          - ec2:DescribeLaunchTemplateVersions
          Resource: '*'
        - Effect: Allow
          Action: 
          - autoscaling:SetDesiredCapacity
          - autoscaling:TerminateInstanceInAutoScalingGroup
          - ec2:DescribeImages
          - ec2:GetInstanceTypesFromInstanceRequirements
          - eks:DescribeNodegroup
          Resource: '*'
```
