### ISSUE TITLE
[Bug] Wrong kube-proxy addon version when upgrading EKS to 1.26

### ISSUE THREAD

**Issue by ustndagsemih** [eksctl-io/eksctl#6700]
Hello,

We upgraded our cluster to 1.26 using eksctl and after that we tried to update kube-proxy.

However when we run describe-addon-versions command, it returns AddonVersion "v1.26.4-eksbuild.1" as latest available but when we upgrade kube-proxy, it runs with the image kube-proxy:v1.26.5-eksbuild.1.

```
2023-06-16 07:09:15 [ℹ]  Kubernetes version "1.26" in use by cluster xxx
2023-06-16 07:09:15 [ℹ]  describing addon versions for addon: kube-proxy
{
  "Addons": [
    {
      "AddonName": "kube-proxy",
      "AddonVersions": [
        {
          "AddonVersion": "v1.26.4-eksbuild.1",
          "Architecture": [
            "amd64",
            "arm64"
          ],
          "Compatibilities": [
            {
              "ClusterVersion": "1.26",
              "DefaultVersion": false,
              "PlatformVersions": [
                "*"
              ]
            }
          ],
          "RequiresConfiguration": false
        },
...
```

I think this should also return kube-proxy:v1.26.5-eksbuild.1.

**Comment by abdennour** [comment]
@ustndagsemih  please share your eksctl cluster YAML definition ( kind: Cluster)

**Comment by ustndagsemih** [comment]
Hello,

Here is simplified version of my cluster definition. 

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-east-1
  version: "1.26"

availabilityZones:

vpc:
  cidr: "x.x.x.x/x"
  nat:
    gateway: x

managedNodeGroups:
  ...
  ...

cloudWatch:
  clusterLogging:

iam:
  withOIDC: true
  serviceAccounts:
    ...
    ...

addons:
  - name: vpc-cni
    version: v1.12.6-eksbuild.2
    attachPolicyARNs:
      ...
      ...
```
