### ISSUE TITLE
How to create inbound rule into cluster security group while create cluster.

### ISSUE THREAD

**Issue by PawXQ** [eksctl-io/eksctl#6802]
Hi everyone,

I use yml file and eksctl command to create my cluster.

For now with aws support reponse if Cluseter Endpoint allow privateAccess, and control instance in same VPC it will connect to api server in private network.

But with create cluster by yaml file, it doesn't create inbound rule for which ec2 that create eks allow to connect to  api server, so i have to additional manual addition inbound rule to security group.

I create cluster and nodegroup in sperate.

How can I put config inbound rule in the ymla file.

**Comment by TiberiuGC** [comment]
Hi @PawXQ , could you try adding the following to your nodegroup config? 

```
nodeGroups:
  - name: xxxx
    iam:
      withAddonPolicies:
        awsLoadBalancerController: true

```
