### ISSUE TITLE
[Bug] Managed nodes unable to join to cluster

### ISSUE THREAD

**Issue by boskiv** [eksctl-io/eksctl#6856]
```
Resource handler returned message: "[Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster, ResourceIds=[i-06674baeb5e93d782, i-0c36741a8b0694281, i-0ef7266d7edb1860a])] (Service: null, Status Code: 0, Request ID: null)" (RequestToken: 2d9f01c5-a52b-0402-252c-e91a0046feb1, HandlerErrorCode: GeneralServiceException)
```

Here is a config file
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sf-cluster
  region: ap-northeast-1
  version: "1.27"
  tags:
    karpenter.sh/discovery: sf-cluster
vpc:
  cidr: 10.10.0.0/16
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
iam:
  withOIDC: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 30

iamIdentityMappings:
  - arn: arn:aws:iam::625332060816:role/OrganizationAccountAccessRole
    username: admin
    groups:
      - system:masters
    noDuplicateARNs: true # prevents shadowing of ARNs

addons:
  - name: vpc-cni
    version: latest
  - name: kube-proxy
    version: latest
  - name: coredns
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true
      certManager: true
      awsLoadBalancerController: true
      externalDNS: true
      imageBuilder: true

karpenter:
  version: 'v0.29.0' # Exact version must be provided
  createServiceAccount: true # default is false
  withSpotInterruptionQueue: true # adds all required policies and rules for supporting Spot Interruption Queue, default is false

managedNodeGroups:
  - name: ng-nats
    instanceTypes:
      - c6a.large
    spot: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true
    desiredCapacity: 3
    labels:
      node.k8s/role: nats
      node-role.kubernetes.io/nats: nats
    taints:
      - key: node.k8s/role
        value: nats
        effect: NoSchedule

  - name: ng-db
    instanceTypes:
      - c6a.large
    spot: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true
    desiredCapacity: 3
    labels:
      node.k8s/role: timescaledb
      node-role.kubernetes.io/nats: timescaledb
    taints:
      - key: node.k8s/role
        value: timescaledb
        effect: NoSchedule

  - name: ng-sf
    instanceTypes:
      - c6a.large
    spot: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true
    desiredCapacity: 3
    labels:
      node.k8s/role: sf
      node-role.kubernetes.io/sf: sf
    taints:
      - key: node.k8s/role
        value: sf
        effect: NoSchedule

  - name: ng-jobs
    minSize: 1
    maxSize: 20
    spot: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true
    instanceTypes:
      - c6a.large
    desiredCapacity: 1
    labels:
        node.k8s/role: jobs
        node-role.kubernetes.io/jobs: jobs
    taints:
      - key: node.k8s/role
        value: jobs
        effect: NoSchedule

  - name: ng-default
    instanceType: c6a.large
    minSize: 1
    maxSize: 10
    desiredCapacity: 2
    labels:
      node.k8s/role: default
      node-role.kubernetes.io/default: default
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true
```
