### ISSUE TITLE
[Bug] Cluster creation fails if no nodegroups and EFS csi addon required 

### ISSUE THREAD

**Issue by kryczech** [eksctl-io/eksctl#6954]
### What were you trying to accomplish?
I wanted to create a cluster with no nodegroups and the aws-efs-csi-driver addon.
I want to create the cluster without nodes because I need to create ENIConfigs for custom networking after the cluster is created, but before any nodes join the cluster.

### What happened?
The cluster creates; however, eksctl exits with an error because the aws-efs-csi-driver addon is degraded since there are no nodes and it can't run the minimum number of replicas. Once nodes are added, the addon will become active, but I need eksctl to not finish with an error code because of the build pipeline will fail.

### How to reproduce it?
Build a cluster with a cluster-config.yaml with no nodegroups, but with efs-csi-driver addon enabled.

```
cluster-config.yaml:
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1
  version: "1.24"
  tags:
    TAG1: tag 1 value
    TAG2: tag 2 value

vpc:
  id: vpc-XXXXXXXXXXX
  securityGroup: sg-XXXXXXXXXXX
  clusterEndpoints:
    publicAccess:  false
    privateAccess: true
  subnets:
    private:
      us-east-1c: 
        id: subnet-XXXXXXXXXXXXXXX
      us-east-1d:
        id: subnet-XXXXXXXXXXXXXXX
      us-east-1a:
        id: subnet-XXXXXXXXXXXXXXX

addons:
- name: vpc-cni
  configurationValues: "{\"env\":{\"AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG\":\"true\", \"ENI_CONFIG_LABEL_DEF\":\"topology.kubernetes.io/zone\"}}"
  version: latest
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  wellKnownPolicies:      # add IAM and service account
    ebsCSIController: true
- name: aws-efs-csi-driver
  wellKnownPolicies:      # add IAM and service account
    efsCSIController: true

iam:
  withOIDC: true
```

**Logs**
```
End of the output from eksctl create cluster -f cluster-config.yaml:
2023-08-11 18:08:49 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-addon-aws-efs-csi-driver"
2023-08-11 18:09:19 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-addon-aws-efs-csi-driver"
2023-08-11 18:10:11 [ℹ]  waiting for CloudFormation stack "eksctl-test-cluster-addon-aws-efs-csi-driver"
2023-08-11 18:10:11 [ℹ]  creating addon
2023-08-11 18:10:22 [!]  1 error(s) occurred while creating addons
2023-08-11 18:10:22 [✖]  addon status transitioned to "DEGRADED"
Error: failed to create addons
```

**Anything else we need to know?**
This looks to be exactly the same issue as https://github.com/eksctl-io/eksctl/issues/5891 but for the EFS csi driver addon instead of the EBS csi driver addon. 5891 was fixed in PR https://github.com/eksctl-io/eksctl/pull/5929

**Versions**

```
$ eksctl info
```
$ eksctl info
eksctl version: 0.150.0-dev
kubectl version: v1.24.13-eks-0a21954
OS: linux
