### ISSUE TITLE
[Bug] eksctl can not create iamserviceaccount

### ISSUE THREAD

**Issue by TerafalgarSMKO** [eksctl-io/eksctl#6966]
### What happened?

When creating a iamserviceaccount for the aws-loadbalancer-controller (https://docs.aws.amazon.com/de_de/eks/latest/userguide/aws-load-balancer-controller.html) with the eksctl command 
When executed ```kubectl get sa -n kube-system | grep aws-load-balancer-controller``` there is no load-balancer-controller in the list

### How to reproduce it?

Execute the  iamserviceaccount create command on a eks cluster with eksctl version 0.151.0
In my case it was:
```bash
eksctl create iamserviceaccount \
  --cluster=eks-lab-test \
  --namespace=kube-system \ 
  --name=aws-load-balancer-controller \
  --role-name AmazonEKSLoadBalancerControllerRole \
  --region eu-central-1 \
  --attach-policy-arn=$ARN \
  --approve
```

### Alternatives

If you are Running into the same issue you can alternatively push the code into a yaml file modify it and use kubectl to create the iamserviceaccount.
This step then creates a the iamserviceaccount without eksctl.
```yaml
cat >aws-load-balancer-controller-service-account.yaml <<EOF      
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/AmazonEKSLoadBalancerControllerRole
EOF
kubectl apply -f aws-load-balancer-controller-service-account.yaml
```

**Versions**

```
$ eksctl info
0.151.0
```
