### ISSUE TITLE
[Bug] eksctl fail to delete cluster if the Application load balancer name created by Ingress is 31 characters

### ISSUE THREAD

**Issue by arestuzi** [eksctl-io/eksctl#7028]
### What were you trying to accomplish?

#  eksctl delete cluster --name eks-workshop 

### What happened?

1. eksctl version - latest version
After execute eksctl delete cluster --name eks-workshop , it returns following error.
2023-08-30 16:45:42 [ℹ]  deleting EKS cluster "eks-workshop"
2023-08-30 16:45:42 [ℹ]  will drain 0 unmanaged nodegroup(s) in cluster "eks-workshop"
2023-08-30 16:45:42 [ℹ]  starting parallel draining, max in-flight of 1
2023-08-30 16:45:43 [ℹ]  deleted 0 Fargate profile(s)
2023-08-30 16:45:43 [✔]  kubeconfig has been updated
2023-08-30 16:45:43 [ℹ]  cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress
Error: cannot obtain information for ALB from Ingress nginx/nginx-ingress: cannot obtain security groups for ALB abc5ca85-default-terryares-5555-: cannot describe ELB: operation error Elastic Load Balancing v2: DescribeLoadBalancers, https response error StatusCode: 400, RequestID: xxxxx-8a5d-xxxxx-bed9-e47c9f844965, api error ValidationError: The load balancer name '0abc5ca85-default-terryares-5555-' cannot end with a hyphen(-)

related code: 
https://github.com/eksctl-io/eksctl/blob/0c2ced9b2f3ec5613d6ef3a7be5327dae1f62b67/pkg/elb/cleanup.go#L220

### How to reproduce it?
Include ALL the steps to reproduce the bug.
1. deploy a ingress with annotation alb.ingress.kubernetes.io/load-balancer-name: "abc5ca85-default-terryares-5555"
2. eksctl delete cluster --name eks-workshop  delete the cluster
If using a config file, include it here, removing any sensitive information!
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: nginx
  name: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: nginx
  name: nginx-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: "abc5ca85-default-terryares-5555"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80
```
