### ISSUE TITLE
[Help] Error: no iamserviceaccounts match include glob filter specification

### ISSUE THREAD

**Issue by trombini77** [eksctl-io/eksctl#7046]
### What were you trying to accomplish?
I tried to using a eksctl yaml file to include after the EKS cluster was created, a ServiceAccount like this:

YAML BLOCK:

```
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: Loki_S3
        # if no namespace is set, "default" will be used;
        # the namespace will be created if it doesn't exist already
        namespace: default
        labels: {aws-usage: "application"}
      attachPolicyARNs:
        - "arn:aws:iam::000000000:policy/Loki-Staging-01"
      tags:
        environment: "staging"
```
command executed: `eksctl create iamserviceaccount --config-file="eksctl_cluster_file.yaml" --include="Loki_S3"`

The documentation https://eksctl.io/usage/iamserviceaccounts/#usage-with-config-files says that command supports `--include` and `--exclude` flags.

### What happened?
```
Error: no iamserviceaccounts match include glob filter specification: "Loki_S3"
```

### How to reproduce it?

**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl info
eksctl version: 0.153.0
kubectl version: v1.27.1-eks-2f008fe
OS: windows
```
and
```
$ eksctl info
eksctl version: 0.155.0
kubectl version: v1.27.1-eks-2f008fe
OS: windows
```
