### ISSUE TITLE
Problems with nodegroups added into 1.27 cluster -  EXTERNAL-IP - <none>

### ISSUE THREAD

**Issue by yoplait** [eksctl-io/eksctl#7062]
## Introduction

Issues when creating a Kubernetes cluster on 1.27 worker nodes but not with 1.26 worker nodes.
We use eksctl to set the EKS control plain and then to create nodegroup

## Versions

``` 
eksctl version
0.154.0-dev+f73436487.2023-08-24T11:48:09Z
``` 

## What happened?

We are creating EKS clusters on 1.27 version.

We have our own AMI custom that was working perfectly fine in 1.26, in facts the nodes are able to run workloads on that.

When creating the node group after a while some checks must fail and the CloudFormation breaks and rollback and then node group and extra workers disappear.

We were checking the pod creating and it was fine for a while, no errors listed and the nodes appear with a strange behaviour, when in 1.26 they have public IPs, on this case they don’t.

## Files and commands?
Main EKS: cluster.yaml
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ami-testing-cluster
  version: "1.27"
  region: us-east-1

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: false
 
```

Node pool: cluster_eks_nodepool.yaml

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ami-testing-cluster
  version: "1.27"
  region: us-east-1

managedNodeGroups:
  - name: ami-testing-nodepool
    labels: { role: workers }
    ami: ami-onefor1.27
    amiFamily: AmazonLinux2
    instanceType: m6i.large
    volumeSize: 20
    disableIMDSv1: false
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/jcp-company.pub
    overrideBootstrapCommand: |
      #!/bin/bash
      eks_register.sh ami-testing-cluster
    iam:
      withAddonPolicies:
        externalDNS: true
        ebs: true
        autoScaler: true
        cloudWatch: false
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
```

## Cluster Status

for a while the cluster appears fine, in command-line
```
IETWDKFH0Y9G:/ jper0017$ kubectl get nodes -o wide
NAME                             STATUS   ROLES    AGE   VERSION   INTERNAL-IP      EXTERNAL-IP     OS-IMAGE                           KERNEL-VERSION             CONTAINER-RUNTIME
ip-192-168-17-150.ec2.internal   Ready    <none>   13m   v1.27.4   192.168.17.150   <none>          Rocky Linux 8.8 (Green Obsidian)   6.1.27-3.amzn.el8.x86_64   containerd://1.6.9
ip-192-168-28-3.ec2.internal     Ready    <none>   50m   v1.26.6   192.168.28.3     3.84.179.188    Rocky Linux 8.8 (Green Obsidian)   6.1.27-3.amzn.el8.x86_64   containerd://1.6.9
ip-192-168-34-172.ec2.internal   Ready    <none>   50m   v1.26.6   192.168.34.172   3.222.245.222   Rocky Linux 8.8 (Green Obsidian)   6.1.27-3.amzn.el8.x86_64   containerd://1.6.9
ip-192-168-51-228.ec2.internal   Ready    <none>   13m   v1.27.4   192.168.51.228   <none>          Rocky Linux 8.8 (Green Obsidian)   6.1.27-3.amzn.el8.x86_64   containerd://1.6.9
IETWDKFH0Y9G:/ jper0017$
```
Even the POD allocation
```
IETWDKFH0Y9G:eks-image-testing jper0017$ kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE     IP               NODE                             NOMINATED NODE   READINESS GATES
kube-system   aws-node-7kfgm             1/1     Running   0          6m44s   192.168.34.172   ip-192-168-34-172.ec2.internal   <none>           <none>
kube-system   aws-node-7q9tm             1/1     Running   0          6m44s   192.168.28.3     ip-192-168-28-3.ec2.internal     <none>           <none>
kube-system   aws-node-9zpq2             1/1     Running   0          30s     192.168.50.233   ip-192-168-50-233.ec2.internal   <none>           <none>
kube-system   aws-node-xx9d9             1/1     Running   0          30s     192.168.9.118    ip-192-168-9-118.ec2.internal    <none>           <none>
kube-system   coredns-79df7fff65-h6f8j   1/1     Running   0          150m    192.168.2.224    ip-192-168-28-3.ec2.internal     <none>           <none>
kube-system   coredns-79df7fff65-p5tpz   1/1     Running   0          150m    192.168.12.190   ip-192-168-28-3.ec2.internal     <none>           <none>
kube-system   kube-proxy-6m78j           1/1     Running   0          6m44s   192.168.28.3     ip-192-168-28-3.ec2.internal     <none>           <none>
kube-system   kube-proxy-8jspq           1/1     Running   0          30s     192.168.9.118    ip-192-168-9-118.ec2.internal    <none>           <none>
kube-system   kube-proxy-k42j2           1/1     Running   0          6m44s   192.168.34.172   ip-192-168-34-172.ec2.internal   <none>           <none>
kube-system   kube-proxy-sftd4           1/1     Running   0          30s     192.168.50.233   ip-192-168-50-233.ec2.internal   <none>           <none>
```

and then after a while they are gone when cloud formation fails:

``` 
ManagedNodeGroup	

CREATE_FAILED

Resource handler returned message: "[Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster, ResourceIds=[i-0a20e93366bc71615, i-0d8dffd040670a8ec])] (Service: null, Status Code: 0, Request ID: null)" (RequestToken: 91041eef-92b7-87f8-3ed0-fc65c81b5fea, HandlerErrorCode: GeneralServiceException)
```

Then:
```
eksctl-ami-testing-cluster-nodegroup-ami-testing-nodepool	
ROLLBACK_IN_PROGRESS
The following resource(s) failed to create: [ManagedNodeGroup]. Rollback requested by user.
```

Same bootstrap script on 1.26 nodes has no problems, for 1.27 we added the logic for kubelet image credential provider

The logs show that the pull works as expected.

The files under:

``` 
/tmp/describe_cluster_result.txt

/etc/kubernetes/pki
/etc/kubernetes/kubelet_eks
/etc/kubernetes/kubeconfig
/etc/kubernetes/kubelet.json
```

Looks the same on 1.26 and 1.27 nodes with the difference of the image credential provider

``` 
[vagrant@ip-192-168-28-3 log]$ sudo cat /etc/kubernetes/kubelet_eks
# TODO: Parametrize further?
KUBELET_EKS_ARGS=--node-ip=192.168.28.3 \
--pod-infra-container-image=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause-amd64:3.1 \
--cloud-provider aws \
--config /etc/kubernetes/kubelet.json \
--kubeconfig /etc/kubernetes/kubeconfig \
--container-runtime remote \
--container-runtime-endpoint unix:///var/run/containerd/containerd.sock
```

vs 1.27

```
[vagrant@ip-192-168-31-163 ~]$ cat sudo cat /etc/kubernetes/kubelet_eks
cat: sudo: No such file or directory
cat: cat: No such file or directory
# TODO: Parametrize further?
KUBELET_EKS_ARGS=--node-ip=192.168.31.163 \
--pod-infra-container-image=602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause-amd64:3.1 \
--config /etc/kubernetes/kubelet.json \
--kubeconfig /etc/kubernetes/kubeconfig \
--image-credential-provider-config /etc/kubernetes/image-credential-provider/config.json \
--image-credential-provider-bin-dir /etc/kubernetes/image-credential-provider
```

### Forgot to say
- AWS VPC works as expected, it has availability of public IPs on the Subnet, it has NAT gateway and everything as the other nodes in 1.26 works
- Account has credits and resources to spin more resources
- We tested a few times to avoid hipcups or other network glitches but the results are always the same, we sping 1.27 eks, we add nodes in 1.26 and it works and we add 1.7 nodes and they are faulted
- No bad signals or things in logs --- journalctl gits for
``` 
journalctl -f -u kubelet
journalctl -u kubelet
journalctl -f -u containerd
journalctl -u containerd
journalctl -f -u cloud-init
journalctl -u cloud-init
```
[gist kubelet and containerd](https://gist.github.com/yoplait/8c8aadf2143fa6d6775dabc6a98aa2ab)
[kube-proxy](https://gist.github.com/yoplait/79f1631ce2414f65223d17902525ec63)

And in relation to services
```
IETWDKFH0Y9G:/ jper0017$ kubectl get services -A

NAMESPACE     NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
default       kubernetes   ClusterIP   10.100.0.1    <none>        443/TCP         6h25m
kube-system   kube-dns     ClusterIP   10.100.0.10   <none>        53/UDP,53/TCP   6h25m
```
:+1: last but not least thanks for the time reading this! :shipit:
