### ISSUE TITLE
[Bug] Launching self-managed node group in Local Zones fail if account is allow-listed to Wavelength Zones and Local Zones

### ISSUE THREAD

**Issue by rhbelson** [eksctl-io/eksctl#7202]
### What were you trying to accomplish?
In trying to launch a self-managed node group in Local Zones, I used 

```
eksctl create cluster --timeout 30m0s -f - << EOF
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_REGION}
  version: "1.25"
  tags:
    environment: ${CLUSTER_NAME}
localZones: ["us-west-2-lax-1a", "us-west-2-las-1a"]
nodeGroups:
  - name: local-ng
    localZones: ["us-west-2-las-1a"]
    instanceType: t3.xlarge
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    volumeType: gp2
managedNodeGroups:
  - instanceType: c6g.xlarge
    amiFamily: AmazonLinux2
    name: ${CLUSTER_NAME}-ng
    desiredCapacity: 0
    minSize: 0
    maxSize: 3
iam:
  withOIDC: true
EOF
```

### What happened?
eksctl failed to create the node group because of the following error:

```
2023-10-19 18:31:05 [✖]  could not find public subnets for zones ["us-west-2-las-1a"] (allSubnets=v1alpha5.AZSubnetMapping{"us-west-2-las-1a":v1alpha5.AZSubnetSpec{ID:"subnet-0ff0cac384615f1f2", AZ:"us-west-2-las-1a", CIDR:(*ipnet.IPNet)(0xc000c552c0), CIDRIndex:0, OutpostARN:""}, "us-west-2-lax-1a":v1alpha5.AZSubnetSpec{ID:"subnet-0fbfc2d5a0c70cc05", AZ:"us-west-2-lax-1a", CIDR:(*ipnet.IPNet)(0xc000c555c0), CIDRIndex:0, OutpostARN:""}} localZones=[]string{"us-west-2-las-1a"} subnets=[]string(nil)): failed to select subnet us-west-2-las-1a: error discovering zone types: expected zone type to be local or AZ; got wavelength-zone
```
The error message reads **got wavelength-zone**, however the subnet in reference (subnet-0fbfc2d5a0c70cc05) is 100% a Local Zone (see below):
```
aws ec2 describe-subnets --subnet-id subnet-0fbfc2d5a0c70cc05
{
    "Subnets": [
        {
            "AvailabilityZone": "us-west-2-lax-1a",
            "AvailabilityZoneId": "usw2-lax1-az1",
            "AvailableIpAddressCount": 4091,
```
When recreating this cluster from an AWS Account only allow-listed to Local Zones but not Wavelength Zones, no such error occurs.

**Versions**
```
$ eksctl info

eksctl version: 0.162.0
kubectl version: v1.22.6-eks-7d68063
OS: linux
```
