### ISSUE TITLE
Configure Amazon EKS worker nodes to clean up the image cache at a specified percent of disk usage

### ISSUE THREAD

**Issue by rfarro82** [eksctl-io/eksctl#7247]
### What feature/behavior/change do you want?
I would like the ability to configure Amazon EKS worker nodes to clean up the image cache at a specified percent of disk usage as called out in https://repost.aws/knowledge-center/eks-worker-nodes-image-cache in the cluster config.yaml. This could be:
```
nodeGroups:
  - name: nodes
    kubeletExtraConfig:
      imageGCHighThresholdPercent: 70
      imageGCLowThresholdPercent: 50
```

### Why do you want this feature?

This would help our runners free up garbage collection space. Currently docker builds caches images and only freed up at 
85%.
