### ISSUE TITLE
[Feature] Expose option to configure local instance SSD as root volume and use for emptydir for managed node groups

### ISSUE THREAD

**Issue by afirth** [eksctl-io/eksctl#7341]
### What feature/behavior/change do you want?

upstream [bootstrap.sh now supports `--local-disks [raid0|mount]`](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L35) which allows, via the `raid0` option, using NVMe SSDs as the root disk of a node. This is particularly useful for fast scratch storage as `emptyDir`.

This feature has been native in GKE since 1.25, however I could not find how to enable it in EKS. There are only [instructions](https://aws.amazon.com/blogs/containers/eks-persistent-volumes-for-instance-store/) for using the local-volume-static-provisioner, which gives you static PVs - difficult to bind to stateless workloads.

In the end I realized I could get this working by calling [`setup-local-disks raid0`](https://github.com/awslabs/amazon-eks-ami/pull/1171/files#diff-7e1d3c800e4dded9b301177d05a4b7f9e3a4ef60f8d7365ead1c3f2af95bc792) script directly in `preBootstrapCommands`, but this is frankly just luck. It would be better to drive it through bootstrap.sh args or env vars.

I think this is a powerful feature and should be exposed by the eksctl api.

## Implementation
I imagine it could be driven by setting the env var in [makeBootstrapEnv](https://github.com/eksctl-io/eksctl/blob/7af49fed33301657cb1447cf7ffb891990f6c1ad/pkg/nodebootstrap/userdata.go#L164), for example

It might be useful to add a label to the nodes as well

### Why do you want this feature?

Data processing jobs and caches often benefit a lot from local disk. Local NVMe is substantially cheaper, and faster, than EBS

#### eksctl config
```yaml
      tags:
        <<: *common-tags
        k8s.io/cluster-autoscaler/node-template/label/local-ssd: pv-nvme
        k8s.io/cluster-autoscaler/node-template/taint/local-ssd: "pv-nvme:NoSchedule"
      labels:
        <<: *common-labels
        local-ssd: pv-nvme
      taints:
      - key: local-ssd
        value: pv-nvme
        effect: NoSchedule
      preBootstrapCommands:
        - |
          setup-local-disks raid0
```

#### sample deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-test
  namespace: local-storage
spec:
  selector:
    matchLabels:
      app: local-test
  template:
    metadata:
      labels:
        app: local-test
    spec:
      tolerations:
      - effect: NoSchedule
        key: local-ssd
        operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: local-ssd
                operator: Exists
      containers:
      - name: test-container
        image: ubuntu:latest
        command:
        - /bin/sh
        args:
        - -c
        - while true; do echo $(date -u); lsblk; df -h --total; sleep 60; done
        volumeMounts:
        - name: empty-dir
          mountPath: /data
      volumes:
      - name: empty-dir
        emptyDir:
          sizeLimit: 1Gi
```

**Comment by cartermckinnon** [comment]
This looks pretty clean to me:
```
preBootstrapCommands:
        - |
          setup-local-disks raid0
```

But I agree that adding a label would be useful. We can handle that on the AMI end.

**Comment by afirth** [comment]
@cartermckinnon I agree that it is clean now, but it seemed like pure luck that the script is [executed](https://github.com/awslabs/amazon-eks-ami/pull/1171/files#diff-049390d14bc3ea2d7882ff0f108e2802ad9b043336c5fa637e93581d9a7fdfc2R222) inside bootstrap.sh relatively early and without side effects. To me the api is the bootstrap.sh args/env vars surface, but you probably know more about that than me. If that hadn't been the case, I would have been stuck baking a custom AMI and using overrideBootstrapCommand, unless I'm missing something

**Comment by cartermckinnon** [comment]
We've learned the hard way that tightly-coupling `eksctl` with the AMI's bootstrap process is a bad idea, so I think it's better to use `preBootstrapCommand`, `overrideBootstrapCommand`, etc. to do things like this instead of making it a typed field in the `eksctl` config schema.

> it seemed like pure luck that the script is [executed](https://github.com/awslabs/amazon-eks-ami/pull/1171/files#diff-049390d14bc3ea2d7882ff0f108e2802ad9b043336c5fa637e93581d9a7fdfc2R222) inside bootstrap.sh relatively early and without side effects.

This was intentional and we won't break that assumption. The `setup-local-disks` helper script can be used standalone as well, it's not going away.

We're rewriting the bootstrap program for our AL2023-based AMI's, and will likely prepare the local SSD for use by default.

**Comment by afirth** [comment]
sounds good. In that case perhaps an update to the [blog post](https://aws.amazon.com/blogs/containers/eks-persistent-volumes-for-instance-store/) and some documentation is all that's required to expose this feature. It felt like pure luck (and a tribute to open source) that I was able to stumble on the helper script

**Comment by akmalmasud96** [comment]
> ### 
> In the end I realized I could get this working by calling [`setup-local-disks raid0`](https://github.com/awslabs/amazon-eks-ami/pull/1171/files#diff-7e1d3c800e4dded9b301177d05a4b7f9e3a4ef60f8d7365ead1c3f2af95bc792) script directly in `preBootstrapCommands`, but this is frankly just luck. It would be better to drive it through bootstrap.sh args or env vars.


Hi @afirth , 
I want to ask that how did you call the setup-local-disk from the preBootstrap-command. 
I am a beginner with Kubernetes, and I want to use that. Can you please inform me about that.

**Comment by afirth** [comment]
@akmalmasud96 
> Hi @afirth , I want to ask that how did you call the setup-local-disk from the preBootstrap-command. I am a beginner with Kubernetes, and I want to use that. Can you please inform me about that.

Since it's available on PATH and executable, just `setup-local-disks raid0`. A more complete config snippet is in the issue description
```yaml
      preBootstrapCommands:
        - |
          setup-local-disks raid0
```

**Comment by akmalmasud96** [comment]
@afirth Thanks for the quick reply.
And the tags, taints and labels which you have  provided, are those necessary to use ?
```
      tags:
        k8s.io/cluster-autoscaler/node-template/label/local-ssd: pv-nvme
        k8s.io/cluster-autoscaler/node-template/taint/local-ssd: "pv-nvme:NoSchedule"
      labels:
        local-ssd: pv-nvme
      taints:
      - key: local-ssd
        value: pv-nvme
        effect: NoSchedule
```

Additionally, I would like to know if support is available in the current EKS AMI version?
