### ISSUE TITLE
[Bug] Cluster Deletion fails with "Error: deadline surpassed waiting for AWS load balancers to be deleted"

### ISSUE THREAD

**Issue by fbuchmeier-abi** [eksctl-io/eksctl#7548]
### What were you trying to accomplish?

I'm trying to delete a eksctl managed cluster that contains AWS Application Loadbalancers managed by the aws-lb-controller (https://kubernetes-sigs.github.io/aws-load-balancer-controller).

### What happened?

Cluster deletion times out with the error below:

```sh
"cmd": [
        "eksctl",
        "delete",
        "cluster",
        "--region",
        "eu-central-1",
        "--name",
        "sandbox",
        "--wait"
    ],
}

STDOUT:

2024-02-09 20:02:45 [ℹ]  deleting EKS cluster "sandbox"
2024-02-09 20:02:46 [ℹ]  will drain 0 unmanaged nodegroup(s) in cluster "sandbox"
2024-02-09 20:02:46 [ℹ]  starting parallel draining, max in-flight of 1
2024-02-09 20:02:46 [ℹ]  deleted 0 Fargate profile(s)
2024-02-09 20:02:47 [✔]  kubeconfig has been updated
2024-02-09 20:02:47 [ℹ]  cleaning up AWS load balancers created by Kubernetes objects of Kind Service or Ingress


STDERR:

Error: deadline surpassed waiting for AWS load balancers to be deleted: k8s-sharedtools-5732128751
```

### How to reproduce it?

1. Deploy a new EKS cluster (I used 1.28) with eksctl >= 0.144.0 and the `vpc-cni` addon
1. Provision the aws-lb-controller as described in the docs: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/deploy/installation/
1. Set up an ingress referencing an Application Loadbalancer. In my case, I am using annotations on the Ingress object:

    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
    annotations:
        alb.ingress.kubernetes.io/group.name: tools
        alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
        alb.ingress.kubernetes.io/healthcheck-path: /api/health
        alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "2"
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
        alb.ingress.kubernetes.io/ssl-redirect: "443"
        alb.ingress.kubernetes.io/success-codes: 200-302
    ```

1. wait until the loadbalancer has been successfully created
1. Delete the EKS cluster

    ```sh
    eksctl delete cluster --region eu-central-1 --name sandbox --wait
    ```

**Anything else we need to know?**

According to my research, the problem occurs because the AWS VPC CNI (aws-node daemonset) is deleted prior to the deletion of associated Kubernetes services and ingress objects. Deleting the CNI daemonset means that the aws-lb-controller pods fail process the finalizers for these objects. The objects then get stuck and can not be deleted in Kubernetes.

For me the cluster deletion process is like follows:

1. VPC CNI gets deleted: https://github.com/aaroniscode/eksctl/blob/main/pkg/actions/cluster/owned.go#L95
2. Shared resources get deleted: https://github.com/aaroniscode/eksctl/blob/main/pkg/actions/cluster/owned.go#L105
3. Shared resources include AWS LB: https://github.com/aaroniscode/eksctl/blob/main/pkg/actions/cluster/delete.go#L63
4. AWS LB now (since PR: https://github.com/eksctl-io/eksctl/pull/6389) include deletion of AWS LB Controller managed resources: https://github.com/aaroniscode/eksctl/blob/08bd92c91037ca21ec18c04277d9d6ba4d21d704/pkg/elb/cleanup.go#L96C2-L96C18

This issue is happening for me since the upgrade to >= 0.144: https://github.com/eksctl-io/eksctl/releases/tag/v0.144.0 and was probably introduced with: https://github.com/eksctl-io/eksctl/pull/6389

**Versions**

```
eksctl info
eksctl version: 0.169.0
kubectl version: v1.24.10
OS: linux
```

Best regards,
Florian.

**Comment by sohrabjs** [comment]
Try the instructions here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-delete.html

These are the steps to delete an Application Load Balancer:

If you have a CNAME record for your domain that points to your load balancer, point it to a new location and wait for the DNS change to take effect before deleting your load balancer.
Open the Amazon EC2 console at https://console.aws.amazon.com/ec2/
On the navigation pane, under LOAD BALANCING, choose Load Balancers.
Select the load balancer, and then choose Actions, Delete.
When prompted for confirmation, choose Yes, Delete.

I have got same error but when I deleted load balancer from amazon console directly and then I ran again the command 
$ eksctl delete cluster --name <cluster-name>  --region us-east-1

It deleted successfully.

**Comment by fbuchmeier-abi** [comment]
Thanks, that sounds reasonable. For the time being I've implemented a similar routine where I get all Ingress and Service resources  from the cluster first, filter them for any that are related to the aws-loadbalancer-controller(*) and then delete the associated Kubernetes resource. Only when they have been successfully deleted I continue to delete the cluster.

(*)
- Services can be of `spec.loadBalancerClass == 'service.k8s.aws/nlb`
- Ingresses can be of `spec.ingressClassName == 'alb'`
- or they can have the following annotation `metadata.annotations."kubernetes.io/ingress.class" == 'alb'`

**Comment by dscreve** [comment]
> Thanks, that sounds reasonable. For the time being I've implemented a similar routine where I get all Ingress and Service resources from the cluster first, filter them for any that are related to the aws-loadbalancer-controller(*) and then delete the associated Kubernetes resource. Only when they have been successfully deleted I continue to delete the cluster.
> 
> (*)
> 
> * Services can be of `spec.loadBalancerClass == 'service.k8s.aws/nlb`
> * Ingresses can be of `spec.ingressClassName == 'alb'`
> * or they can have the following annotation `metadata.annotations."kubernetes.io/ingress.class" == 'alb'`

Could you describe which commands are you using to fix this ?

**Comment by fbuchmeier-abi** [comment]
I use ansible to get all ingresses and services provisioned by the aws-lb-controller and then delete them. The code looks like this:

```
- name: Get all ingresses
  kubernetes.core.k8s_info:
    kind: Ingress
  register: _ingress

- name: Get all services
  kubernetes.core.k8s_info:
    kind: Service
  register: _service

- name: Select only ingresses and services that are managed by aws-lb-controller
  vars:
    service_query: >
      [?spec.loadBalancerClass == 'service.k8s.aws/nlb']
    ingress_class_query: >
      [?spec.ingressClassName == 'alb']
    ingress_annotation_query: >
      [?metadata.annotations."kubernetes.io/ingress.class" == 'alb']
  set_fact:
    to_delete_services: "{{ _service['resources'] | community.general.json_query(service_query) }}"
    to_delete_ingresses: "{{ _ingress['resources'] | community.general.json_query(ingress_class_query) + _ingress['resources'] | community.general.json_query(ingress_annotation_query) }}"

- name: Ensure aws-lb-controller managed resources are removed
  vars:
    kind: "{{ item['kind'] }}"
    name: "{{ item['metadata']['name'] }}"
    namespace: "{{ item['metadata']['namespace'] }}"
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: "{{ kind }}"
    name: "{{ name }}"
    namespace: "{{ namespace }}"
    continue_on_error: true
  with_items: "{{ to_delete_services + to_delete_ingresses }}"
  register: tbd_result
  loop_control:
    label: "Deleted {{ kind }} {{ namespace }}/{{ name }}"
```
