### ISSUE TITLE
[Bug] Inf2 Managed Node Groups should have used Amazon Linux 2 GPU Optimized AMI    

### ISSUE THREAD

**Issue by lindarr915** [eksctl-io/eksctl#7683]
### What were you trying to accomplish?

I'm creating an EKS Node Group with Inf2 instances 

### What happened?

The managed node group does not use Amazon Linux 2 GPU Optimized AMI. 
I would expect it use  Amazon Linux 2 GPU Optimized AMI that includes Neuron device drivers. 

### How to reproduce it?

```
# my-neuron-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-neuron-cluster
  region: us-west-2  # Replace with your desired AWS region

managedNodeGroups:
  - name: inf2-node-group
    instanceType: inf2.8xlarge
    minSize: 1  
    maxSize: 4 
    desiredCapacity: 2 
```
**Logs**

**Anything else we need to know?**

**Versions**

```
$ eksctl info
❯ eksctl version
eksctl version: 0.173.0-dev+a7ee89342.2024-03-01T03:40:57Z
kubectl version: v1.29.2
```
