### ISSUE TITLE
[Bug] "non-functional in v1.16+; use the "priorityClassName" field instead" warning during eksctl deployment

### ISSUE THREAD

**Issue by jackylu0124** [eksctl-io/eksctl#7717]
### What were you trying to accomplish?

I am trying to create a EKS cluster with the `eksctl create cluster -f cluster.yaml` command (see my `cluster.yaml` file content in the reproduction section).

### What happened?

I saw the following warning in the log during cluster creation:
```
4400 warnings.go:70] spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
```
### How to reproduce it?

Run `eksctl create cluster -f cluster.yaml` on the following config file (`cluster.yaml`):
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster-001
  region: us-east-1

vpc:
  autoAllocateIPv6: false
  cidr: 10.108.0.0/16

managedNodeGroups:
- name: ng-0
  desiredCapacity: 1
  maxSize: 1
  minSize: 1
  instanceType: g4dn.xlarge
  volumeSize: 50
```

**Logs**

Warning log:
```
4400 warnings.go:70] spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
```
**Anything else we need to know?**

My OS is Windows 11, and I used the downloaded binary.
**Versions**

```
$ eksctl info
eksctl version: 0.175.0
kubectl version: v1.27.2
OS: windows
```
