### ISSUE TITLE
AL2023 UserData Available Documentation

### ISSUE THREAD

**Issue by AbeOwlu** [eksctl-io/eksctl#7749]
### What help do you need?

There isnt a clear wording in documentation that: "users NEED to create a launch template if custom userData (script) is required for Amazon Linux 2023"
- `overrideBootstrapCommand` interface is no longer available.
- Not sure how [this UserData](https://github.com/eksctl-io/eksctl/blob/4cc7918e5006b5d994a15270160961d11eb50d32/pkg/nodebootstrap/al2023.go#L54) in nodebootsrap al23 is used, but the configuration below also is not valid
```
managedNodeGroups:
  - name: custAMIGroup
    ami: ami-079fcd733303590b9
    amiFamily: AL23
    userData: |
      MIME-Version: 1.0 
      Content-Type: multipart/mixed; boundary="BOUNDARY"      
      
      --BOUNDARY 
      Content-Type: text/x-shellscript; charset="us-ascii"

      #!/bin/bash
      echo "exec custom script here"
      
      --BOUNDARY--

      Content-Type: application/node.eks.aws      
      --- 
      apiVersion: node.eks.aws/v1alpha1 
      kind: NodeConfig 
      spec:
        cluster:
          apiServerEndpoint:
          certificateAuthority:
          cidr:
          name:

      --BOUNDARY--
```
- [a documentation somewhere should specifically point this out?](https://github.com/eksctl-io/eksctl/blob/4cc7918e5006b5d994a15270160961d11eb50d32/pkg/nodebootstrap/README.md#amazonlinux2023) e.g
```
While AL2023 implements the Bootstrapper interface, the underlying userdata will be entirely different from other AMI families. Specifically, AL2023 introduces a new node initialization process nodeadm that uses a YAML configuration schema, dropping the use of /etc/eks/bootstrap.sh script. For self-managed nodes, and for EKS-managed nodes based on custom AMIs, eksctl will populate userdata in the fashion below:
...
Required custom cloud-init scripts are no longer merged into a bootstrap.sh execution, and custom launch templates need to be defined to execute custom scripts on node bootstrap.
...
```
