### ISSUE TITLE
`migrate-to-pod-identity` incorrectly updates EKS addons to use pod identity

### ISSUE THREAD

**Issue by cPu1** [eksctl-io/eksctl#7752]
When running `eksctl utils migrate-to-pod-identity --remove-oidc-provider-trust-relationship --approve` on a cluster where a managed EKS addon like `vpc-cni` is using IRSA, it incorrectly migrates the addon to use pod identity by removing the OIDC provider trust relationship from the service account role and removing the IRSA annotation, potentially breaking the addon for older versions that do not support pod identity. EKS addons do not officially support pod identity (although newer versions work), so they should be skipped during migration. 

A sample config to reproduce this issue:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: us-west-2

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
```
