### ISSUE TITLE
Managed node group not creating anymore 

### ISSUE THREAD

**Issue by alexsluborski77** [eksctl-io/eksctl#7780]
Hi, i am using EKSCTL to configure a managed node group for an existing AWS EKS cluster. 
I succesfully created it last night with no issues. Had the node group running and was able to scale. Now I needed to add some more configurations and so I deleted the node group using` eksctl delete nodegroup <nodegroupname> --cluster <clustername>`

Today, I did it again, applying the config file using eksctl  but now it doesnt create the node group 
this is the output
`eksctl create nodegroup -f cluster-nodegroup.yaml
2024-05-23 13:23:08 [ℹ]  will use version 1.29 for new nodegroup(s) based on control plane version
2024-05-23 13:23:08 [!]  no eksctl-managed CloudFormation stacks found for "TestCluster", will attempt to create nodegroup(s) on non eksctl-managed cluster
2024-05-23 13:23:10 [ℹ]  1 task: { no tasks }
2024-05-23 13:23:10 [ℹ]  no tasks
2024-05-23 13:23:10 [✔]  created 0 nodegroup(s) in cluster "TestCluster"
2024-05-23 13:23:10 [✔]  created 0 managed nodegroup(s) in cluster "TestCluster"`

This seems to not be receiving a task to create the node group. I tried to create a new cluster and used my original config ( just added gp3 to volume) and now it doesn't seem to be working at all. Did I break something running delete nodegroup? I'm not sure what to do. I restarted my computer, I really don't know why it just stopped working all of a sudden.

This is my config:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: TestCluster # Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
  region: us-east-2

vpc:
  id: xxxxxxxxxxxxxxxx  # Replace with your VPC ID
  securityGroup: xxxxxxxxxxxxxxxx
  subnets:
    public:
      us-east-2a:
        id: subnet-xxxxxxxxxxxxx  # Replace with your first private subnet ID
      us-east-2b:
        id: subnet-xxxxxxxxxxxxx  # Replace with your second private subnet ID
    private:
      us-east-2a:
        id: subnet-xxxxxxxxxxxxx  # Replace with your first private subnet ID
      us-east-2b:
        id: subnet-xxxxxxxxxxxxx  # Replace with your second private subnet ID


NodeGroups:
  - name: nodegroup1
    instanceType: p3.2xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    amiFamily: AmazonLinux2
    ami: auto
    volumeSize: 200
    iam:
      instanceRoleARN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    subnets:
      - subnet-xxxxxxxxxxxxx  # Replace with your first private subnet ID
      - subnet-xxxxxxxxxxxxx  # Replace with your second private subnet ID
    privateNetworking: true
```
