### ISSUE TITLE
[Bug] Degraded managedNodeGroups when using a pathed instanceRoleARN

### ISSUE THREAD

**Issue by matschaffer-roblox** [eksctl-io/eksctl#7846]
### What were you trying to accomplish?

We launch EKS clusters using instanceRoleARN to attach managed policies (`AmazonEKSWorkerNodePolicy`, `AmazonEKS_CNI_Policy`, `AmazonEC2ContainerRegistryReadOnly`) to our node group instances.

We provided a `path` on these roles of ` "/eks/"` for organizational purposes. We'd like to be able to manage these node groups, but the pathing seems to cause a degradation in node group health.

### What happened?

The cluster creates as expected but after about an hour or so the node group shows up as degraded

![Screenshot_2024-06-23_at_9_16_37 PM](https://github.com/eksctl-io/eksctl/assets/115565899/d6bee150-d29f-40a3-9541-77077e4dc7ef)

![Screenshot_2024-06-23_at_9_17_41 PM](https://github.com/eksctl-io/eksctl/assets/115565899/25e1d127-11d4-4cc0-8b5d-b20173e231a1)

It's a little tough to tell with the redactions, but the ARN shown in the "Affected resources" column lacks the `/eks/` path prefix.

Removing the path parameter from the role seems to avoid the issue.

### How to reproduce it?

We use a eksctl config template like this:

```
managedNodeGroups:
  - name: stable-{{ .CLUSTER_NAME_WITH_HYPHENS }}
    instanceType: r5.8xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    privateNetworking: true
    volumeSize: 40
    volumeType: gp3
    volumeEncrypted: true
    labels:
      stable: "true"
    tags:
      <<: *tags
    iam:
      instanceRoleARN: {{ .STABLE_NODES_ROLE_ARN }}
```

Where the instance role ARN is `"arn:aws:iam::ACCOUNT:role/eks/ROLE_NAME"`

**Logs**

Output from eksctl during creation is normal.

**Anything else we need to know?**

What OS are you using? macos
Are you using a downloaded binary or did you compile eksctl? downloaded via asdf
What type of AWS credentials are you using (i.e. default/named profile, MFA)? SSO

**Versions**

```
❯ eksctl info   
eksctl version: 0.183.0
kubectl version: v1.30.2
OS: darwin
```
