### ISSUE TITLE
[Bug] could not create cluster provider from options: managedNodeGroups[0].overrideBootstrapCommand - 0.183.0

### ISSUE THREAD

**Issue by shyam-ks** [eksctl-io/eksctl#7852]
Getting the following error - 
Error: could not create cluster provider from options: managedNodeGroups[0].overrideBootstrapCommand is not supported when using a custom AMI based on AmazonLinux2023 (managedNodeGroups[0].ami)
```
managedNodeGroups:
  - name: "ng-1-workers-27-Jun-2024-T13-30-09"
    subnets:
      - ext-sub-1
    instanceType: "m5.2xlarge"
    desiredCapacity: 2
    labels: { role: workers }
    tags:
      env: dev
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

      withAddonPolicies:
        ebs: true
        cloudWatch: true
    privateNetworking: true
    volumeSize: 200
    volumeEncrypted: true
    securityGroups:
      attachIDs: ["sg-xxxxxxxxxxxxxx"]
    ami: ami-xxxxxxxxxxxxx
    amiFamily: AmazonLinux2023 
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh dev
```
