### ISSUE TITLE
Nodes of a NodeGroup with AMI type BOTTLEROCKET_x86_64_NVIDIA are not joining the cluster

### ISSUE THREAD

**Issue by cPu1** [eksctl-io/eksctl#7897]
_The customer used eksctl to create a managed node group with the gpus set to 0 in the instance selector and specified the AMI family as Bottlerocket. Under these settings, a normal Bottlerocket AMI was expected to be configured, but the customer's managed node group was configured with an NVIDIA Bottlerocket variant, causing instances to fail to load kernel modules_.

Nodegroup config:

```yaml
    name: worker-1c-spot-2-v5
    availabilityZones: ["eu-central-1c"]
    spot: true
    minSize: 0
    desiredCapacity: 1
    maxSize: 60
    privateNetworking: true
    amiFamily: Bottlerocket
    taints:
      - key: nodegroup
        value: worker
        effect: NoSchedule
    propagateASGTags: true
    instanceSelector:
      vCPUs: 8
      memory: 16GiB
      cpuArchitecture: x86_64
      gpus: 0
```
