### ISSUE TITLE
[Bug] CapacityReservationResourceGroupArn being ignored in eksctl create cluster

### ISSUE THREAD

**Issue by junpuf** [eksctl-io/eksctl#7906]
### What were you trying to accomplish?

We ran `eksctl create cluster` with a yaml config like below. The goal is to have a cluster standing up and using CapacityReservationResourceGroupArn.

FYI: someone has reported this issue 2 years ago seems not yet fixed https://repost.aws/questions/QUaid5sRdmRu2OFi7SQyxytg/eks-managed-nodegroup-with-capacity-reservation-in-launch-template-through-cloudformation-does-not-use-capacity-reservation

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-dev
  region: us-west-2

AMI
  - name: p4d
    instanceType: p4d.24xlarge
    minSize: 0
    maxSize: 37
    desiredCapacity: 2
    availabilityZones: ["us-west-2a"]
    volumeSize: 2048
    ssh:
      publicKeyName: ...
    efaEnabled: true
    privateNetworking: true
    capacityReservation:
      capacityReservationTarget:
        CapacityReservationResourceGroupArn: <our resource group arn>
```

### What happened?

The generated ec2 launch template is missing the `CapacityReservationResourceGroupArn` and as result, we are not able to use our capacity resource group.

For example, it will generate cfn that have CapacityReservationTarget set to {}.

```
...
 "LaunchTemplate": {
      "Type": "AWS::EC2::LaunchTemplate",
      "Properties": {
        "LaunchTemplateData": {
          "BlockDeviceMappings": [
            {
              "DeviceName": "/dev/xvda",
              "Ebs": {
                "Iops": 3000,
                "Throughput": 125,
                "VolumeSize": 2048,
                "VolumeType": "gp3"
              }
            }
          ],
          "CapacityReservationSpecification": {
            "CapacityReservationTarget": {}
...
```

### How to reproduce it?

Create a capacity resource group and use it in cluster config yaml and run `eksctl create cluster`. Then you can check the generated cloud formation template or the ec2 launch template to see that it doesn't have CapacityReservationResourceGroupArn. 

**Logs**

**Anything else we need to know?**

Default EKS Optimized AMI, 
we used https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_amd64.tar.gz

**Versions**

```
$ eksctl info
```
