### ISSUE TITLE
[Bug] EKS Access Entries are not applying the second exec after entry be deleted in console.

### ISSUE THREAD

**Issue by VictorLopess** [eksctl-io/eksctl#7907]
### What were you trying to accomplish?

I'm creating access-entries like doc: https://eksctl.io/usage/access-entries/

In the first apply, command works correctly. I deleted an specific entry and tried to run again, but the message returned is `ℹ]  access entries already up-to-date`. But it's not correct because they do not created another new entry in the EKS.

### What happened?

Command: `eksctl create accessentry -f config.yaml`

My struct:
```
accessConfig:
  accessEntries:
    - principalARN: arn:aws:iam::1111111111:user/USERNAME
      type: STANDARD
      accessPolicies: # optional access polices
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster
```

### How to reproduce it?

- Create a simple cluster configuration
- Add a access-entries like:
```
accessConfig:
  accessEntries:
    - principalARN: arn:aws:iam::1111111111:user/USERNAME
      type: STANDARD
      accessPolicies: # optional access polices
        - policyARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
          accessScope:
            type: cluster
```

- Run: `eksctl create accessentry -f config.yaml`
- Go to the EKS AWS Console and delete the created entry
- Try to running  `eksctl create accessentry -f config.yaml` again. It can't see there is an change to do returning _access entries already up-to-date_

**Logs**

`2024-07-29 22:08:27 [ℹ]  access entries already up-to-date`
**Anything else we need to know?**

**Versions**

```
$ eksctl info:
eksctl version: 0.187.0
kubectl version: v1.29.6
OS: linux

```
