### ISSUE TITLE
[Bug] Creation of managed node groups failed: alpha.eksctl.io/nodegroup-type is not a valid tag key

### ISSUE THREAD

**Issue by Ankitwasnik** [eksctl-io/eksctl#7948]
### What were you trying to accomplish?

I was trying to create a cluster using a config file. See the config file below.

### What happened?

Cluster got created but creation of managed node groups failed. I see the following error message in cloudformation.
`
Resource handler returned message: "'alpha.eksctl.io/nodegroup-type' is not a valid tag key. Tag keys must match pattern ([0-9a-zA-Z\\-_+=,.@:]{1,255}), and must not be a reserved name ('.', '..', '_index') (Service: Eks, Status Code: 400, Request ID: 'some id')" (RequestToken: 'some id', HandlerErrorCode: InvalidRequest)
`

### How to reproduce it?

Copy the following config to a file. Run the command `eksctl create cluster -f config.yaml`. 
See the cloudformation logs. 
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mycluster-1
  region: us-west-2
  version: "1.30"

kubernetesNetworkConfig:
  ipFamily: IPv4

managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 2
    maxSize: 3
    volumeSize: 80
    volumeEncrypted: true
    volumeKmsKeyID: '' 
    volumeType: 'gp3'
    ssh:
      publicKeyPath: ~/workspace/key.pub
availabilityZones: ["us-west-2a", "us-west-2b",  "us-west-2c"]
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true

addons:
  - name: vpc-cni
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
```

**Logs**

https://gist.github.com/Ankitwasnik/eb56f9bedab1d223ec6b601908d17fc4
**Anything else we need to know?**

What OS are you using? Ubuntu 22.04.4 LTS 
Are you using a downloaded binary or did you compile eksctl? Downloaded binary
What type of AWS credentials are you using (i.e. default/named profile, MFA)? - Named profile

**Versions**

```
eksctl version: 0.189.0
kubectl version: v1.30.0
OS: linux
```
