### ISSUE TITLE
[Feature] aws-load-balancer-controller addon

### ISSUE THREAD

**Issue by pbarker** [eksctl-io/eksctl#7993]
### What feature/behavior/change do you want?
A simple was to add aws-load-balancer-controller  to a cluster

### Why do you want this feature?
Because most clusters need ingress and its still very cumbersome to do so

**Comment by cPu1** [comment]
AWS Load Balancer Controller is not available as an EKS addon yet. We do not have any plans to support self-managed versions of addons. You can track this [issue](https://github.com/aws/containers-roadmap/issues/1162) for more details.

**Comment by skubot** [comment]
@pbarker It's quite easy to setup AWSLoadBalancerController...
in your cluster.yaml add...
```yaml
iam:
  podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: aws-load-balancer-controller
      createServiceAccount: true
      wellKnownPolicies:
        awsLoadBalancerController: true
addons:
  - name: eks-pod-identity-agent
  - name: vpc-cni
    podIdentityAssociations:
      - namespace: kube-system
        serviceAccountName: aws-node
        permissionPolicyARNs: ['arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy']
```
then using helm...
```
helm repo update eks

helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
  -n kube-system \
  --set clusterName=${CLUSTER_NAME} \
  --set region=us-west-2 \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller
```
