### ISSUE TITLE
[Help] eksctl CRD's installation

### ISSUE THREAD

**Issue by raghu-manne** [eksctl-io/eksctl#7995]
### What help do you need?

I am trying to setup ALB LoadBalancer Controlller using [this ](https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/deploy/installation/#option-a-recommended-iam-roles-for-service-accounts-irsa), while doing this setup I am facing issue which is already raised here #7987.

Workaround mentioned in #7987 has a config file used with eksctl to create service account, I tried to create the ClusterConfig with both the policies but the eksctl CRD's are missing. How do I install the eksctl CRD's?

eksctl command executed: `eksctl create iamserviceaccount --cluster=cluster_name --namespace=kube-system --name=aws-load-balancer-controller --attach-policy-arn=arn:aws:iam:${AWS_ACCOUNT_ID}:policy/AWSLoadBalancerControllerIAMPolicy --override-existing-serviceaccounts --region us-east-1 --approve`

ClusterConfig File:

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster_name
  region: us-east-1
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    attachPolicyARNs:
    - arn:aws:iam:${AWS_ACCOUNT_ID}:policy/AWSLoadBalancerControllerIAMPolicy
    attachPolicy: |
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
           Action:
             - elasticloadbalancing:DescribeListenerAttribute
             - elasticloadbalancing:ModifyListenerAttribute
           Resource: "*"
    wellKnownPolicies:
      awsLoadBalancerController: true
``` 
Error while applying the file:

```
$ k apply -f alb-lbc-irsa-eksctl.yml
error: resource mapping not found for name: "test-2" namespace: "" from "alb-lbc-irsa-eksctl.yml": no matches for kind "ClusterConfig" in version "eksctl.io/v1alpha5"ensure CRDs are installed first
```

Help needed in installing eksctl CRD's, TIA!
