### ISSUE TITLE
[Feature] Support instanceTypes override when using custom LaunchTemplate

### ISSUE THREAD

**Issue by youwalther65** [eksctl-io/eksctl#8044]
### What feature/behavior/change do you want?

Currently trying to create a managed node group (MNG) with custom LaunchTemplate and **instanceTypes** like this
```yaml
managedNodeGroups:
- name: mng-custom-AL2023
  minSize: 1
  maxSize: 2
  desiredCapacity: 2
  instanceTypes: [ "m6gd.large", "m7gd.large" ]
  launchTemplate:
    id: lt-089fa9a17a94857cd
    version: 5
  updateConfig:
    maxUnavailable: 1
```
leads to the following error
```bash
$ eksctl create nodegroup -f eksctl-NVME-AL2023.yaml
Error: couldn't create node group filter from command line options: loading config file "eksctl-NVME-AL2023.yaml": json: cannot unmarshal number into Go struct field LaunchTemplate.managedNodeGroups.launchTemplate.version of type string
````

### Why do you want this feature?

A LaunchTemplate only supports just one **InstanceType** , therefore having it in the MNG as an instance override is the only way to have instance diversification which helps to avoid running into InsufficientInstanceCapacity errors.
