### ISSUE TITLE
[Bug] EKS AutoMode: iam.serviceRoleARN: InsufficientCapabilitiesException: Requires capabilities : [CAPABILITY_IAM]

### ISSUE THREAD

**Issue by byoungsoo** [eksctl-io/eksctl#8069]
### What were you trying to accomplish?
Create EKS Auto Mode clutser using eksctl. [Refer to document](https://docs.aws.amazon.com/eks/latest/userguide/automode-get-started-eksctl.html)

### What happened?
```
eksctl create cluster -f cluster.yaml

2024-12-02 22:52:32 [✖]  creating CloudFormation stack "eksctl-eks-auto-mode-test-cluster": operation error CloudFormation: CreateStack, https response error StatusCode: 400, RequestID: c9069de8-24df-4c84-b60d-0ec7c514add8, InsufficientCapabilitiesException: Requires capabilities : [CAPABILITY_IAM]
```

### How to reproduce it?

`eksctl create cluster -f cluster.yaml`
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-auto-mode-test
  region: ap-northeast-2

iam:
  serviceRoleARN: arn:aws:iam::111122223333:role/EKSClusterServiceRole

autoModeConfig:
  enabled: true
```

**Anything else we need to know?**

If I remove `serviceRoleARN config`, it successfully create stack.

**Versions**

```
eksctl version
0.196.0
```
