### ISSUE TITLE
[Bug] Can't disable default addons with auto mode

### ISSUE THREAD

**Issue by artem-nefedov** [eksctl-io/eksctl#8164]
### What were you trying to accomplish?

Create a cluster with auto mode enabled and with default addons (metrics-server) disabled.

### What happened?

eksctl throws a confusing error (no mention of problematic section). Removing `addonsConfig` makes the creation run successfully.

### How to reproduce it?

Run `eksctl create cluster` with config containing the following sections:

```yaml
addonsConfig:
  disableDefaultAddons: true

autoModeConfig:
  enabled: true
  nodeRoleARN: arn:...<redacted>
  nodePools: [system] 

iam:
  withOIDC: true
  serviceAccounts:
   ... # non-empty list required for the problem to trigger
```

**Logs**

```
Error: fields nodeGroups, managedNodeGroups, fargateProfiles, karpenter, gitops, iam.serviceAccounts, and iam.podIdentityAssociations are not supported during cluster creation in a cluster without VPC CNI; please remove these fields and add them back after cluster creation is successful
```

**Anything else we need to know?**

**Versions**

eksctl 0.202.0
