### ISSUE TITLE
[Bug]  The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI

### ISSUE THREAD

**Issue by gaussye** [eksctl-io/eksctl#8235]
When use eksctl to create nodegroup, it should auto launch the ami based on the instance type. However for some arm instance types like x8g.16xlarg, it failed to load the right ami. i got error when create nodegroup for the yaml below: 
Resource handler returned message: "You must use a valid fully-formed launch template. The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-east-1
  version: '1.31'
managedNodeGroups:
  - name: test-ng
    instanceType: x8g.16xlarge
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
```

If I change the instanceType to m6g.medium. I works properly.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster
  region: us-east-1
  version: '1.31'
managedNodeGroups:
  - name: test-ng
    instanceType: m6g.medium
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
```

**Comment by dims** [comment]
@gaussye is `x8g.16xlarg` a typo? missing `e`?

**Comment by dims** [comment]
just tried the following `eksctl create cluster -f test.yaml` and it picked up the right `arm` based AMI.

<img width="1164" alt="Image" src="https://github.com/user-attachments/assets/ed5d2dbc-bb00-4fc9-b466-1be0b3fe51e0" />

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-cluster-3
  region: us-west-2
  version: '1.31'
managedNodeGroups:
  - name: test-ng
    instanceType: x8g.16xlarge
    amiFamily: AmazonLinux2
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
```
