### ISSUE TITLE
[Help] Tagging ENIs in EKS cluster

### ISSUE THREAD

**Issue by steffakasid** [eksctl-io/eksctl#8263]
### What help do you need?
For compliance reasons we apply certain tags on All AWS resources we deploy. Therefore we also define tags in our eksctl cluster yaml.
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  [...]
  tags:
    Group: Groups
    ReferenceName: Reference
    ReferenceID: 1234
    CostReference: abce-45423
    Contact: our@email.com
    TechnicalContactMail: our@email.com
    SecurityContactMail: our@email.com
    Environment: test
```
And also on the nodegroups:
```
nodeGroups:
  - name: {{ $nodeGroupElement.name }}-{{ $availabilityZoneElement }}-{{ $deployMode }}
    [...}
    tags:
      Group: Groups
      ReferenceName: Reference
      ReferenceID: 1234
      CostReference: abce-45423
      Contact: our@email.com
      TechnicalContactMail: our@email.com
      SecurityContactMail: our@email.com
      Environment: test
```

Right now I found out that we have two ENIs per cluster which aren't tagged at all. I turns out that those ENIs belong to the EKS ControlPlane (as basically described here: https://repost.aws/questions/QUIkhPjRVBTqWzm4AutiPqHg/how-eks-control-plane-is-communicate-with-worker-nodeJ).

I verified this by doing:
![Image](https://github.com/user-attachments/assets/77a3b7df-0682-437b-89bb-f682695b07f4)

![Image](https://github.com/user-attachments/assets/f58be16c-458a-4fa9-8468-690ffcd5c5d1)

Is there any possibilit to apply tags to those ENIs?

**Sidenote**:
We tagged the clusters manually as the clusters are already running for years (production ~5 years) and we could not recreate them because of non acceptable downtimes when doing so. Maybe we need to do something here to apply it with eksctl?
