### ISSUE TITLE
[Feature] ClusterConfig to support for YAML anchors and aliases

### ISSUE THREAD

**Issue by guessi** [eksctl-io/eksctl#8270]
[YAML-ANCHORS-ALIASES]: https://yaml.org/spec/1.2.2/#anchors-and-aliases

### What feature/behavior/change do you want?

By current design, `eksctl` not able to accept `ClusterConfig` with [YAML anchors or aliases][YAML-ANCHORS-ALIASES]. If there have any unsupported entry, it would emit error as follow,

```shell
Error: couldn't create node group filter from command line options: loading config file "./clusterConfig.yaml": error unmarshaling JSON: while decoding JSON: json: unknown field "aliases"
```

### Why do you want this feature?

If ClusterConfig could support [YAML anchors or aliases][YAML-ANCHORS-ALIASES], we could turn [1] to [2].

### [1] BEFORE

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo

managedNodeGroups:
  - name: generic-1
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy

  - name: generic-2
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy

  - name: minimal-1
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodeMinimalPolicy

  - name: minimal-2
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodeMinimalPolicy
```

### [2] AFTER

```yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

aliases: # By current design, it would cause template parsing error
  genericAttachPolicyARNs: &genericAttachPolicyARNs
  - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy

  minimalAttachPolicyARNs: &minimalAttachPolicyARNs
  - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  - arn:aws:iam::aws:policy/AmazonEKSWorkerNodeMinimalPolicy

metadata:
  name: eks-demo

managedNodeGroups:
  - name: generic-1
    iam:
      attachPolicyARNs: *genericAttachPolicyARNs

  - name: generic-2
    iam:
      attachPolicyARNs: *genericAttachPolicyARNs

  - name: minimal-1
    iam:
      attachPolicyARNs: *minimalAttachPolicyARNs

  - name: minimal-2
    iam:
      attachPolicyARNs: *minimalAttachPolicyARNs
```
