### ISSUE TITLE
[Bug] Enabling core networking addons to be configured for clusters with a mix of EKS Auto Mode and Hybrid nodes compute

### ISSUE THREAD

**Issue by RobertNorthard** [eksctl-io/eksctl#8292]
### What were you trying to accomplish?

Run eksctl create cluster with a `cluster.yaml` file that has EKS Auto Mode and Hybrid nodes configured along with the required addons (`CoreDNS` and `kube-proxy`). I would expect to be able to configure `kube-proxy` and `coredns` in a cluster that has both EKS Auto Mode and Hybrid nodes compute.

### What happened?

eksctl presented the following error:
````
Error: core networking addons are not required on a cluster using Auto Mode; if you still wish to create them, use `eksctl create addon` post cluster creation
````

### How to reproduce it?

1. Create the following `cluster.yaml`

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster
  region: us-west-2
  version: "1.32"

addonsConfig:
  disableDefaultAddons: true

autoModeConfig:
  enabled: true
  nodePools: ["general-purpose", "system"]

remoteNetworkConfig:
  iam:
    provider: ssm
  remoteNodeNetworks:
  - cidrs: ["172.18.0.0/16"]
  remotePodNetworks:
  - cidrs: ["172.17.0.0/16"]

addons:
  - name: kube-proxy
  - name: coredns
```

2. Run `eksctl create cluster -f cluster.yaml` and get the following message:

**Logs**
N/A

**Anything else we need to know?**
N/A

**Versions**

```
eksctl info
eksctl version: 0.204.0
kubectl version: v1.24.10-eks-48e63af
```
