### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by rjbrown57** [eksctl-io/eksctl#8356]
### What feature/behavior/change do you want?

When using `eksctl utils write-kubeconfig` it would be great if it was possible to set the proxy url in the generated kubeconfig. Something like `eksctl utils write-kubeconfig -c cluster_name --proxy-url myproxyhere:1081`.

```
    - cluster:
        certificate-authority-data: asfdadsf
        server: https://adsfasdf.eks.amazonaws.com
        proxy-url: myproxyhere:1081 # <-- Set this via command line flag
```

### Why do you want this feature?
This is a convenience for people who need to use a proxy and have large numbers of distinct kube-configs.
