### ISSUE TITLE
[Bug] `useDefaultPodIdentityAssociations` does not work with IPv6 cluster even having `attachPolicy` set

### ISSUE THREAD

**Issue by guessi** [eksctl-io/eksctl#8388]
### What were you trying to accomplish?

To make the ClusterConfig setups below works (both).

```
kubernetesNetworkConfig:
  ipFamily: IPv6
...

addons:
  - name: vpc-cni
    version: latest
    useDefaultPodIdentityAssociations: true
```

```
kubernetesNetworkConfig:
  ipFamily: IPv6
...

addons:
  - name: vpc-cni
    version: latest
    useDefaultPodIdentityAssociations: true
    attachPolicy:
       ... (omit)
```

### What happened? and How to reproduce it?

An IPv6 cluster should expected to have [Required IAM permissions for running IPv6 cluster](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/iam-policy.md#ipv6-mode) included.

However, when trying to setup `vpc-cni` with `useDefaultPodIdentityAssociations: true`,

```
kubernetesNetworkConfig:
  ipFamily: IPv6

...
addons:
  - name: vpc-cni
    version: latest
    useDefaultPodIdentityAssociations: true
```

The actual result would have no required permission included, only [AmazonEKS_CNI_Policy](https://docs.aws.amazon.com/eks/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-amazoneks-cni-policy) being added, but "AmazonEKS_CNI_Policy" does not have [Required IAM permissions for running IPv6 cluster](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/iam-policy.md#ipv6-mode).

> NOTE: it was worked before, but I'm not sure which version it started failing.

Trying to fix issue by adding `attachPolicy`, but unfortunately `eksctl` will emit error,

```
kubernetesNetworkConfig:
  ipFamily: IPv6

...
addons:
  - name: vpc-cni
    version: latest
    useDefaultPodIdentityAssociations: true
    attachPolicy: # <---------------------
       ... (omit) # <---------------------
```

Error message if both `useDefaultPodIdentityAssociations: true` and `attachPolicy` set:
```
Error: cannot specify serviceAccountRoleARN, wellKnownPolicies, attachPolicy or attachPolicyARNs when addon.useDefaultPodIdentityAssociations is set (addon: vpc-cni)
```

Due to the error above, even we have `makeIPv6VPCCNIPolicyDocument()` helper function set,
https://github.com/eksctl-io/eksctl/blob/fbfeda6bf566479605150bfc18588cc85450224f/pkg/actions/addon/create.go#L474-L498

It will not walk into the section here,
https://github.com/eksctl-io/eksctl/blob/fbfeda6bf566479605150bfc18588cc85450224f/pkg/actions/addon/create.go#L183-L200

**Anything else we need to know?**

There's a PR #8387 attempts to address this issue with documentation update.

**Versions**

any
