### ISSUE TITLE
[Help] EC2 instances keep getting created and terminated

### ISSUE THREAD

**Issue by er-16** [eksctl-io/eksctl#8423]
Hello everyone,

I recently created an EKS Auto Mode cluster via `eksctl` with no default node pools. Here is my `cluster.yaml`:
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: ap-southeast-1
iam:
  serviceRoleARN: "arn:aws:iam::xxxxxxxxxxxx:role/AmazonEKSAutoClusterRole"
autoModeConfig:
  enabled: true
  nodePools: []
```
After the cluster was provisioned, I created a `nodeclass`:
```yaml
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: eks-system-node-class
spec:
  role: AmazonEKSAutoNodeRole
  subnetSelectorTerms:
    - id: subnet-xxxxxxxxxxxxxxxxx
    - id: subnet-xxxxxxxxxxxxxxxxx
    - id: subnet-xxxxxxxxxxxxxxxxx
  securityGroupSelectorTerms:
    - id: sg-xxxxxxxxxxxxxxxxx
  snatPolicy: Random
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Enabled
  ephemeralStorage:
    size: "80Gi"
    iops: 3000
    throughput: 125
    kmsKeyID: "arn:aws:kms:ap-southeast-1:xxxxxxxxxxxx:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  tags:
    NodeClass: eks-system-node-class
```
and a `nodepool`:
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: eks-system-node-pool
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata: {}
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: eks-system-node-class
      requirements:
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["m6i.large", "m6i.xlarge", "m6i.2xlarge", "m6i.4xlarge", "m6i.8xlarge", "m6i.12xlarge", "m6i.16xlarge", "m6i.24xlarge", "m6i.32xlarge", "m7i.large", "m7i.xlarge", "m7i.2xlarge", "m7i.4xlarge", "m7i.8xlarge", "m7i.12xlarge", "m7i.16xlarge", "m7i.24xlarge", "m7i.48xlarge"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "eks.amazonaws.com/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "eks.amazonaws.com/compute-type"
          operator: In
          values: ["auto"]
        - key: "eks.amazonaws.com/instance-encryption-in-transit-supported"
          operator: In
          values: ["true"]
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["m"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: In
          values: ["6", "7"]
        - key: "eks.amazonaws.com/instance-family"
          operator: In
          values: ["m6i", "m7i"]
        - key: "eks.amazonaws.com/instance-size"
          operator: In
          values: ["large", "xlarge", "2xlarge", "4xlarge", "8xlarge", "12xlarge", "16xlarge", "24xlarge", "32xlarge", "48xlarge"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["2", "4", "8", "16", "32", "48", "64", "96", "128", "192"]
        - key: "eks.amazonaws.com/instance-cpu-manufacturer"
          operator: In
          values: ["intel"]
        - key: "eks.amazonaws.com/instance-memory"
          operator: In
          values: ["4096", "8192", "16384", "32768", "65536", "98304", "131072", "196608", "262144", "393216", "524288", "786432", "1048576", "1572864"]
        - key: "eks.amazonaws.com/instance-ebs-bandwidth"
          operator: In
          values: ["10000", "15000", "20000", "30000", "40000"]
        - key: "eks.amazonaws.com/instance-network-bandwidth"
          operator: In
          values: ["781", "1172", "2344", "4687", "9375", "10000", "12500", "18750", "25000", "37500", "40000", "50000", "100000"]
      taints:
        - key: CriticalAddonsOnly
          effect: NoSchedule
      expireAfter: 336h
      terminationGracePeriod: 24h0m0s
```
However, the metrics server pods were stuck in a pending state, and EC2 instances were continuously being created and terminated immediately. I have confirmed that an EKS Access Entry was created to allow nodes to join the cluster.

Please help me troubleshoot this issue. Thank you in advance.
